// Open Orders — THE operational tracking screen for every active Purchase
// Order: current business status (Approved → Shipped → Delivered, single
// source of truth in models/business-status.js), quantity flow, progress,
// last activity and expected arrival. Related documents live in the Business
// File (the single document navigator on the PO page). Fully delivered POs
// auto-close and move to Purchase History; a PO the supplier cannot complete
// is closed manually here (mandatory reason, audited, remaining quantity
// becomes Cancelled). The expandable Item Details grid exports (Excel / PDF /
// Print) reuse the already-loaded overview rows — no extra queries.
import { mount, delegate, qs } from '../../utils/dom.js';
import { esc, qty } from '../../utils/format.js';
import { loading, emptyState, tableWrap } from '../../components/table/table.js';
import { toast } from '../../components/notifications/toast.js';
import { openOrdersOverview } from '../../services/fulfillment/fulfillment.service.js';
import { closeOrderManually, listReplacementCandidates } from '../../services/purchase-orders/orders.service.js';
import { BIZ_VARIANT, CLOSE_REASONS } from '../../models/business-status.js';
import { exportOpenOrdersExcel } from '../../services/export/business-export.service.js';
import { t } from '../../i18n/i18n.js';

const bizBadge = (s) => `<span class="sc-badge ${BIZ_VARIANT[s] || 'none'}">${esc(s)}</span>`;

export async function render(root, ctx) {
  mount(root, loading('Loading open orders…'));
  let orders;
  try { orders = await openOrdersOverview(); }
  catch (e) { return mount(root, emptyState('⚠', e.message || String(e))); }

  const OPEN_LINES = new Set(); // order ids with the line panel expanded

  paint();
  // delegated once — paint() only swaps innerHTML, so no listener stacking
  delegate(root, {
    open: ({ id }) => ctx.navigate('purchase-orders', { orderId: +id, mode: 'view' }),
    xlsall: async () => { try { await exportOpenOrdersExcel(orders); toast('Open orders exported', 'ok'); } catch (e) { toast(e.message || String(e), 'err'); } },
    lines: ({ id }) => { const n = +id; OPEN_LINES.has(n) ? OPEN_LINES.delete(n) : OPEN_LINES.add(n); paint(); },
    bizfile: ({ id }) => ctx.navigate('business-files', { orderId: +id }),
    xlslines: ({ id }) => exportLinesExcel(orders.find((o) => o.id === +id)),
    pdflines: ({ id }) => openLinesPrintDoc(orders.find((o) => o.id === +id), { pdf: true }),
    printlines: ({ id }) => openLinesPrintDoc(orders.find((o) => o.id === +id), { pdf: false }),
    closepo: ({ id }) => closeDialog(orders.find((o) => o.id === +id)),
  });

  // ---- Item Details dataset — exactly the rows the expanded grid shows -------
  const lineData = (o) => (o.lines || []).map((l) => ({
    ros: l.item_code || l.roshen_id || '', erp: l.roshen_id || '', desc: l.description || '',
    ordered: l.ordered, shipped: l.shipped, delivered: l.delivered, remaining: l.remaining,
    status: l.business_status,
  }));
  const lineTotals = (rows) => rows.reduce((a, r) => ({
    ordered: a.ordered + r.ordered, shipped: a.shipped + r.shipped,
    delivered: a.delivered + r.delivered, remaining: a.remaining + r.remaining,
  }), { ordered: 0, shipped: 0, delivered: 0, remaining: 0 });
  const stamp = () => new Date().toISOString().slice(0, 16).replace('T', ' ');

  function exportLinesExcel(o) {
    if (!o) return;
    if (!window.XLSX) return toast('Excel engine not loaded', 'err');
    const rows = lineData(o), tot = lineTotals(rows);
    const header = ['Roshen Code', 'ERP Item Code', 'Description', 'Ordered Qty', 'Shipped Qty',
      'Delivered Qty', 'Remaining Qty', 'Line Status', 'Purchase Order Number', 'Supplier'].map((h) => t(h));
    const aoa = [header, ...rows.map((r) => [r.ros, r.erp, r.desc, r.ordered, r.shipped,
      r.delivered, r.remaining, r.status, o.order_number, o.supplier || ''])];
    aoa.push([], ['TOTAL', '', '', tot.ordered, tot.shipped, tot.delivered, tot.remaining, '', '', ''],
      ['Generated Date', stamp()], ['Generated By', 'Roshen Supply Chain — Open Orders']);
    const ws = window.XLSX.utils.aoa_to_sheet(aoa);
    ws['!cols'] = header.map((h, i) => ({ wch: Math.min(48, Math.max(String(h).length + 2, ...aoa.slice(1).map((row) => String(row[i] ?? '').length + 2))) }));
    ws['!autofilter'] = { ref: window.XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: rows.length, c: header.length - 1 } }) };
    ws['!freeze'] = { xSplit: 0, ySplit: 1 };
    const wb = window.XLSX.utils.book_new();
    window.XLSX.utils.book_append_sheet(wb, ws, 'Open Order Items');
    window.XLSX.writeFile(wb, `${String(o.order_number || 'order').replace(/[^\w-]+/g, '_')}_open_order_items.xlsx`);
    toast('Item details exported', 'ok');
  }

  // one print document serves both PDF export (landscape, letterhead) and
  // plain Print (the visible table only) — a separate window naturally hides
  // the app navigation, sidebar and buttons
  function openLinesPrintDoc(o, { pdf }) {
    if (!o) return;
    const rows = lineData(o), tot = lineTotals(rows);
    const w = window.open('', '_blank', 'width=1200,height=800');
    if (!w) return toast('Allow pop-ups to export', 'err');
    const cells = (r) => `<td class="mono">${esc(r.ros)}</td><td class="mono">${esc(r.erp)}</td><td>${esc(r.desc)}</td>
      <td class="r">${qty(r.ordered)}</td><td class="r">${qty(r.shipped)}</td><td class="r">${qty(r.delivered)}</td>
      <td class="r"><b>${qty(r.remaining)}</b></td><td>${esc(r.status)}</td>`;
    w.document.write(`<!doctype html><html><head><title>${esc(o.order_number)} — Open Order Items</title><style>
      @page{size:A4 ${pdf ? 'landscape' : 'portrait'};margin:12mm}
      body{font-family:Arial,Helvetica,sans-serif;color:#111;font-size:${pdf ? '10px' : '11px'}}
      h1{font-size:16px;margin:0}.sub{color:#555;font-size:10px;margin:2px 0 10px}
      .logo{font-size:13px;font-weight:800;letter-spacing:.04em;margin-bottom:2px}
      table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:3px 6px;text-align:left;vertical-align:top}
      th{background:#efefef;font-size:9.5px;text-transform:uppercase;letter-spacing:.03em}
      td.r,th.r{text-align:right}.mono{font-family:ui-monospace,Menlo,Consolas,monospace}
      thead{display:table-header-group}tfoot td{font-weight:700;background:#f7f7f7}
      footer{position:fixed;bottom:0;right:0;font-size:8px;color:#888}
    </style></head><body>
      ${pdf ? '<div class="logo">🏭 Roshen / Relia — Supply Chain</div>' : ''}
      <h1>Open Order Items — ${esc(o.order_number)}</h1>
      <div class="sub">Supplier: ${esc(o.supplier || '—')} · Generated ${stamp()} · ${rows.length} line(s)</div>
      <table><thead><tr><th>${t('Roshen Code')}</th><th>${t('ERP Item Code')}</th><th>${t('Description')}</th>
        <th class="r">${t('Ordered')}</th><th class="r">${t('Shipped')}</th><th class="r">${t('Delivered')}</th><th class="r">${t('Remaining')}</th><th>${t('Line Status')}</th></tr></thead>
      <tbody>${rows.map((r) => `<tr>${cells(r)}</tr>`).join('')}</tbody>
      <tfoot><tr><td colspan="3">TOTAL — ${rows.length} line(s)</td>
        <td class="r">${qty(tot.ordered)}</td><td class="r">${qty(tot.shipped)}</td><td class="r">${qty(tot.delivered)}</td>
        <td class="r">${qty(tot.remaining)}</td><td></td></tr></tfoot></table>
      <footer>Roshen / Relia Supply Chain · ${esc(o.order_number)} · page numbers added by the print dialog</footer>
    </body></html>`);
    w.document.close();
    setTimeout(() => { w.print(); }, 400);
  }

  function paint() {
    const tot = orders.reduce((a, o) => ({
      ordered: a.ordered + o.ordered_cases, shipped: a.shipped + o.shipped_cases,
      delivered: a.delivered + o.delivered_cases, remaining: a.remaining + o.remaining_cases,
    }), { ordered: 0, shipped: 0, delivered: 0, remaining: 0 });

    const bar = (p) => `<div style="display:flex;align-items:center;gap:8px"><div style="flex:1;height:6px;border-radius:4px;background:var(--border-light);overflow:hidden;min-width:90px">
      <div style="width:${p}%;height:100%;background:${p >= 100 ? '#2FB344' : '#1971C2'}"></div></div><span style="font-size:11px;color:var(--text-muted);min-width:34px">${p}%</span></div>`;

    const itemCell = (l) => `<td class="oo-item">
      <b class="oo-ros">${esc(l.item_code || l.roshen_id || '')}</b>
      <div class="oo-desc" title="${esc(l.description || '')}">${esc(l.description || '')}</div>
      ${l.roshen_id && l.item_code ? `<div class="oo-erp mono">${esc(l.roshen_id)}</div>` : ''}</td>`;

    const rows = orders.map((o) => {
      const lines = OPEN_LINES.has(o.id) ? `<tr><td colspan="11" style="background:var(--bg-secondary);padding:8px 14px">
        <div class="oo-lines-bar">
          <b style="font-size:12.5px">📦 ${t('Item Details')} — ${esc(o.order_number)}</b>
          <span style="font-size:11px;color:var(--text-muted)">${o.lines.length} line(s)</span>
          <span class="sc-spacer"></span>
          <button class="sc-btn sm ghost" data-act="xlslines" data-id="${o.id}">📊 Export Excel</button>
          <button class="sc-btn sm ghost" data-act="pdflines" data-id="${o.id}">📄 Export PDF</button>
          <button class="sc-btn sm ghost" data-act="printlines" data-id="${o.id}">🖨 Print</button>
        </div>
        ${tableWrap(`<table class="sc-table" style="min-width:0"><thead><tr>
          <th>Item</th><th class="num">Ordered</th><th class="num">Shipped</th><th class="num">Delivered</th><th class="num">Remaining</th><th>Line Status</th></tr></thead><tbody>
          ${o.lines.map((l) => `<tr>
            ${itemCell(l)}
            <td class="num">${qty(l.ordered)}</td><td class="num">${qty(l.shipped)}</td>
            <td class="num">${qty(l.delivered)}</td><td class="num"><b>${qty(l.remaining)}</b></td>
            <td>${bizBadge(l.business_status)}</td></tr>`).join('')}
        </tbody></table>`)}</td></tr>` : '';
      return `<tr class="sc-row-link" data-act="open" data-id="${o.id}">
        <td class="mono"><b>${esc(o.order_number)}</b>
          <button class="sc-btn sm ghost" style="padding:1px 6px;font-size:10px" data-act="lines" data-id="${o.id}" title="line items">${OPEN_LINES.has(o.id) ? '▲' : '▼'}</button></td>
        <td>${esc(o.supplier || '')}</td>
        <td style="font-size:11.5px">${esc(o.order_date || '')}</td>
        <td class="num">${qty(o.ordered_cases)}</td>
        <td class="num">${qty(o.shipped_cases)}</td>
        <td class="num">${qty(o.delivered_cases)}</td>
        <td class="num"><b>${qty(o.remaining_cases)}</b></td>
        <td style="white-space:nowrap">${bizBadge(o.business_status)}</td>
        <td style="min-width:140px">${bar(o.pct)}</td>
        <td style="font-size:11px;color:var(--text-secondary)">${esc(o.last_activity || '—')}${o.next_eta ? '<br>ETA ' + esc(String(o.next_eta).slice(0, 16).replace('T', ' ')) : ''}</td>
        <td style="white-space:nowrap">
          <button class="sc-btn sm ghost" data-act="bizfile" data-id="${o.id}" title="Open the Business File">📁 File</button>
          <button class="sc-btn sm ghost" data-act="closepo" data-id="${o.id}" title="Close this purchase order">✖ Close</button></td></tr>${lines}`;
    }).join('')
      || '<tr><td colspan="11" style="text-align:center;color:var(--text-muted);padding:22px">No open orders — everything is delivered or closed. Completed orders are in Purchase History. 🎉</td></tr>';

    mount(root, `
      <div class="sc-card-h"><h3>⏳ Open Orders</h3>
        <span class="sc-badge none" style="margin-left:8px">${orders.length}</span>
        <div class="sc-spacer"></div>
        <span style="font-size:12.5px;color:var(--text-secondary)">Ordered <b>${qty(tot.ordered)}</b> · Shipped <b>${qty(tot.shipped)}</b> · Delivered <b>${qty(tot.delivered)}</b> · Still expected <b>${qty(tot.remaining)}</b> cases</span>
        <button class="sc-btn ghost sm" style="margin-left:10px" data-act="xlsall">⬇ Excel</button></div>
      <div class="sc-card">
        <p style="font-size:12px;color:var(--text-secondary);margin:0 0 10px">Live business status per order: <b>Approved</b> → <b>Shipped</b> (delivery note confirmed) → <b>Delivered</b> (invoice matched &amp; goods posted). Fully delivered orders move to Purchase History automatically; use ✖ Close when the supplier cannot complete an order.</p>
        ${tableWrap(`<table class="sc-table sc-cardify"><thead><tr>
          <th>PO Number</th><th>Supplier</th><th>Order Date</th>
          <th class="num">Ordered</th><th class="num">Shipped</th><th class="num">Delivered</th><th class="num">Remaining</th>
          <th>Status</th><th>Progress</th><th>Last Activity / ETA</th><th></th></tr></thead>
          <tbody>${rows}</tbody></table>`)}
      </div>
      <div data-el="closemodal"></div>`);
  }

  // ---- manual close dialog (mandatory reason, optional replacement link) ----
  async function closeDialog(o) {
    if (!o) return;
    const candidates = await listReplacementCandidates(o.id).catch(() => []);
    const host = qs('[data-el="closemodal"]', root);
    host.innerHTML = `<div class="sc-modal-overlay open"><div class="sc-modal" style="max-width:520px">
      <h4>Close Purchase Order ${esc(o.order_number)}?</h4>
      <p style="font-size:12.5px;color:var(--text-secondary)">This is a business action, not a delete: the order keeps its full history, the remaining <b>${qty(o.remaining_cases)}</b> cases become <b>Cancelled</b>, no new delivery notes or supplier invoices can be created against it, and it moves to Purchase History.</p>
      <div class="sc-field"><label>Close Reason *</label>
        <select class="sc-select" data-cl="reason"><option value="">— select a reason —</option>
          ${CLOSE_REASONS.map((r) => `<option>${esc(r)}</option>`).join('')}</select></div>
      <div class="sc-field" style="margin-top:8px"><label>Comments <span style="color:var(--text-muted)">(required for “Other”)</span></label>
        <textarea class="sc-input" data-cl="comments" rows="2" placeholder="optional details"></textarea></div>
      <div class="sc-field" style="margin-top:8px"><label>Closed By *</label>
        <input class="sc-input" data-cl="by" placeholder="Your name"></div>
      <div class="sc-field" style="margin-top:8px"><label>Replaced by Purchase Order</label>
        <select class="sc-select" data-cl="repl"><option value="">— none —</option>
          ${candidates.map((r) => `<option value="${r.id}">${esc(r.order_number)}</option>`).join('')}</select></div>
      <div class="sc-modal-actions" style="margin-top:14px">
        <button class="sc-btn" style="background:#E03131;color:#fff" data-cl="confirm">✖ Close Purchase Order</button>
        <button class="sc-btn ghost" data-cl="cancel">Cancel</button>
      </div></div></div>`;
    const v = (k) => { const n = qs(`[data-cl="${k}"]`, host); return n ? n.value.trim() : ''; };
    qs('[data-cl="cancel"]', host).addEventListener('click', () => { host.innerHTML = ''; });
    qs('[data-cl="confirm"]', host).addEventListener('click', async () => {
      const reason = v('reason'), comments = v('comments'), by = v('by'), repl = v('repl');
      if (!reason) return toast('Select a close reason', 'err');
      if (reason === 'Other' && !comments) return toast('Add a comment explaining the reason', 'err');
      if (!by) return toast('Enter who is closing the order', 'err');
      try {
        await closeOrderManually(o.id, { reason, comments, closedBy: by, replacedByOrderId: repl ? +repl : null });
        toast(`Purchase order ${o.order_number} closed — moved to Purchase History`, 'ok');
        host.innerHTML = '';
        orders = await openOrdersOverview();
        paint();
      } catch (e) { toast(e.message || String(e), 'err'); }
    });
  }
}
